### ISSUE TITLE
Error when training DAMSM

### ISSUE THREAD

**Issue by leeeeeeo** [taoxugit/AttnGAN#10]
Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 275, in <module>
    dataset.ixtoword, image_dir)
  File "pretrain_DAMSM.py", line 61, in train
    for step, data in enumerate(dataloader, 0):
  File "/media/server009/seagate/liuhan/anaconda2/envs/attngan/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "/media/server009/seagate/liuhan/anaconda2/envs/attngan/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 180, in __init__
    self._put_indices()
  File "/media/server009/seagate/liuhan/anaconda2/envs/attngan/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 219, in _put_indices
    indices = next(self.sample_iter, None)
  File "/media/server009/seagate/liuhan/anaconda2/envs/attngan/lib/python2.7/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/media/server009/seagate/liuhan/anaconda2/envs/attngan/lib/python2.7/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2184

@taoxugit 
Could you please help me solve this problem?
Thank you very much! 
I'm looking forward to your reply.

**Comment by taki0112** [comment]
did you solve this problem ?
