### ISSUE TITLE
FileNotFoundError: File b'../data/coco\\CUB_200_2011/bounding_boxes.txt' does not exist

### ISSUE THREAD

**Issue by AnwarUllahKhan** [taoxugit/AttnGAN#25]
(base) H:\AttnGAN-master\code>python pretrain_DAMSM.py --cfg cfg/DAMSM/coco.yml --gpu 0
Using config:
{'B_VALIDATION': False,
 'CONFIG_NAME': 'DAMSM',
 'CUDA': True,
 'DATASET_NAME': 'coco',
 'DATA_DIR': '../data/coco',
 'GAN': {'B_ATTENTION': True,
         'B_DCGAN': False,
         'CONDITION_DIM': 100,
         'DF_DIM': 64,
         'GF_DIM': 128,
         'R_NUM': 2,
         'Z_DIM': 100},
 'GPU_ID': 0,
 'RNN_TYPE': 'LSTM',
 'TEXT': {'CAPTIONS_PER_IMAGE': 5, 'EMBEDDING_DIM': 256, 'WORDS_NUM': 15},
 'TRAIN': {'BATCH_SIZE': 48,
           'B_NET_D': True,
           'DISCRIMINATOR_LR': 0.0002,
           'ENCODER_LR': 0.002,
           'FLAG': True,
           'GENERATOR_LR': 0.0002,
           'MAX_EPOCH': 600,
           'NET_E': '',
           'NET_G': '',
           'RNN_GRAD_CLIP': 0.25,
           'SMOOTH': {'GAMMA1': 4.0,
                      'GAMMA2': 5.0,
                      'GAMMA3': 10.0,
                      'LAMBDA': 1.0},
           'SNAPSHOT_INTERVAL': 5},
 'TREE': {'BASE_SIZE': 299, 'BRANCH_NUM': 1},
 'WORKERS': 1}
C:\ProgramData\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 243, in <module>
    transform=image_transform)
  File "H:\AttnGAN-master\code\datasets.py", line 110, in __init__
    self.bbox = self.load_bbox()
  File "H:\AttnGAN-master\code\datasets.py", line 126, in load_bbox
    header=None).astype(int)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'../data/coco\\CUB_200_2011/bounding_boxes.txt' does not exist

**Comment by AnwarUllahKhan** [comment]
Dear researchers, I am facing this problem using coco dataset so how can I found bounding_boxes.txt file for coco dataset?

Thank you very much

**Comment by RaiAbhishek** [comment]
coco dataset does not have or need bounding_boxes.txt file, proceed without it.
![image](https://user-images.githubusercontent.com/29359850/44617487-cb9acc00-a880-11e8-9e80-006603f5cfb0.png)
the above block in file _datasets.py_ already takes care of that, you must have made some changes.
you can simply replace that block by - 
`self.bbox = None`

**Comment by RaiAbhishek** [comment]
coco dataset does not need bounding boxes. proceed with:
`self.bbox = None`

**Comment by AnwarUllahKhan** [comment]
@RaiAbhishek @sethjuarez @taoxugit 

Load from:  ../data/coco\captions.pickle
1 5
Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 246, in <module>
    assert dataset
AssertionError

how can I solve this problem?

**Comment by RaiAbhishek** [comment]
Regarding the above-mentioned issue, there is a backslash in your pathname, change that to forward slash.
About pickle files, captions.pickle file will be generated automatically if not there already, while the pickle files in folders data/train/ and data/test are created manually as per requirement.
Kindly go through code in _pretrain_DAMSM.py_ and _datasets.py_ at least, you will understand the input pipeline.

**Comment by growingfuture** [comment]
I solved it like below

go into the code > cfg > DAMSM 
find the bird.yml and coco.yml
and change below  
DATA_DIR:` '../data/birds'   # write  down your own path instead of ../

Hope to be helpful!
