### ISSUE TITLE
RuntimeError: Couldn't open shared file mapping: <torch_18044_1286185042>, error code: <1455>

### ISSUE THREAD

**Issue by Sadden** [taoxugit/AttnGAN#35]
I tried to run the pre-train part, but it shows like this:
```
  File "pretrain_DAMSM.py", line 274, in <module>
    dataset.ixtoword, image_dir)
  File "pretrain_DAMSM.py", line 59, in train
    for step, data in enumerate(dataloader, 0):
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 135, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 135, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 135, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 135, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 110, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "D:\Work\Aconda\AnacodaPython3.7\envs\py37\lib\site-packages\torch\storage.py", line 114, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_18044_1286185042>, error code: <1455> at C:\Anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\TH\THAllocator.c:157
```
could anyone help me?

**Comment by shaivaldalal** [comment]
Have you made modifications to ensure that your code runs on Python 3.7? The current repo has code compatible for Python 2.7
