### ISSUE TITLE
AttributeError with Easydict

### ISSUE THREAD

**Issue by Naberei** [taoxugit/AttnGAN#84]
I setuped everything and used the command "python main.py --cfg cfg/coco_attn2.yml --gpu 3" but it throw this error:

\Downloads\K.I\AttnGAN\code\miscc\config.py:103: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    cfg_from_file(args.cfg_file)
  File "C:\Users\timon\Downloads\K.I\AttnGAN\code\miscc\config.py", line 105, in cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "C:\Users\timon\Downloads\K.I\AttnGAN\code\miscc\config.py", line 73, in _merge_a_into_b
    for k, v in a.iteritems():
AttributeError: 'EasyDict' object has no attribute 'iteritems'

**Comment by Sathvik-2412** [comment]
Hey, were you able to solve this?

**Comment by ashok2216-A** [comment]
I have fixed this issue:
here is the solution 

def cfg_from_file(filename):
    """Load the configuration from a YAML file."""
    with open(filename, 'r') as f:
        yaml_cfg = edict(yaml.load(f, Loader=yaml.FullLoader))
    return yaml_cfg
